# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qtcurve-qt5

# >> macros
# << macros

Summary:    Qt 5 style
Version:    1.8.15
Release:    1
Group:      System/GUI/Other
License:    GPLv2
URL:        https://github.com/QtCurve/qtcurve-qt5
Source0:    %{name}-%{version}.tar.xz
Source100:  qtcurve-qt5.yaml
Requires:   libxcb >= 1.10
Requires:   qt5-plugin-platform-xcb
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Svg)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(xcb)
BuildRequires:  pkgconfig(xcb-image)
BuildRequires:  cmake

%description
Qt 5 style.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc AUTHORS COPYING README TODO
%{_qt5_plugindir}/styles/qtcurve.so
# >> files
# << files
